name: Pull Request Stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: Demo-Sample/.github/workflows/main.yml@main
        with:
          token: ${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}
          #organization: 'Org-Name'
          Repository: Demo-Sample
          period: 24
          charts: true
          disable-links: true
          sort-by: 'COMMENTS'
